<?php

/**
 * @file
 * Enables user signatures.
 */
use Drupal\comment\CommentInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implement hook_help().
 */
function user_signature_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.user_signature':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The User signature module allows users to set up custom user-specific signatures that are displayed below comments') . '</p>';
      // @todo Check field_ui module enabled.
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Account settings') . '</dt>';
      $output .= '<dd>' . t('The <a href="!accounts">Account settings page</a> allows you to manage settings for the displayed name of the anonymous user role, personal contact forms, user registration, and account cancellation. On this page you can also manage settings for account personalization and adapt the text for the e-mail messages that are sent automatically during the user registration process.', ['!accounts'  => \Drupal::url('entity.user.admin_form')]) . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function user_signature_entity_extra_field_info() {
  $fields['comment']['comment']['display']['user_signature'] = [
    'label' => t('User signature'),
    'description' => t('Comment author user signature.'),
    'weight' => 150,
  ];
  return $fields;
}

/**
 * Implements hook_ENTITY_TYPE_view() for comment entities.
 */
function user_signature_comment_view(array &$build, CommentInterface $comment, EntityViewDisplayInterface $display, $view_mode) {
  $comment_author = $comment->getOwner();
  if ($display->getComponent('user_signature') && $comment_author->isActive() && $comment_author->hasField('user_signature')) {
    // Display signature only for active users with module's field.
    // @todo Provide display settings to view() and get rid of user display.
    $build['user_signature'] = $comment_author->get('user_signature')->view('user_signature');
  }
}
